#!/bin/bash
# map files from sdcard to alien

MOUNTPATH=/home/.media
MEDIAPATH=/run/media/nemo

echo "### alien-mount-sdcard"

if [ -d $MOUNTPATH ]; then
        umount $MOUNTPATH || :
fi

mkdir -p $MOUNTPATH

su -c "bindfs --chmod-ignore --chown-ignore --chgrp-ignore --map=100000/1023:@100000/@1023 --perms=755 $MEDIAPATH $MOUNTPATH"
if [ "$?" != "0" ]; then
    echo "Failed to mount media for alien"
    exit 1
fi
